language: node_js
node_js:
- '0.10'
before_install:
  - gem install sass
  - gem install compass
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_success:
  - grunt build
  - heroku keys:clear
  - yes | heroku keys:add
  - grunt buildcontrol
env:
  global:
    secure: "EV83RaeBdbR9w6CIe5uUM1X0Qs36Ty+5hiXRZbJK075Sf3qiHcuqaHbILmcS8QIup9zWoY/580tAH8Ls8c8cAvYYhfZPoqulbf6VFmNFfz7su3fZs/r4nAJ+dVIK6Gzwm9wYBm9+eiJVOYrU+CTT5+JxyqNIBwfH8C34Gnk5hiI="
